feeder: dataset.dataloader_video.VideoDataset
phase: train
dataset: phoenix2014
num_epoch: 80
work_dir: /sda/data/renjiawei/data_openslr/
batch_size: 2
random_seed: 0
test_batch_size: 2
num_worker: 8
device: 6
log_interval: 200
eval_interval: 1
save_interval: 5
loss_weights:
  ConvCTC: 1.0
  SeqCTC: 1.0
  Dist: 25.0
  Cu: 0.001
  Cp: 0.001

optimizer_args:
  optimizer: Adam
  base_lr: 0.0001
  step: [ 40, 60]
  learning_ratio: 1
  weight_decay: 0.0001
  start_epoch: 0
  nesterov: False

feeder_args:
  mode: 'train'
  datatype: 'memmap'
  num_gloss: -1
  drop_ratio: 1.0
  frame_interval: 1
  image_scale: 1.0

model: models.build_function.build_slowfast
decode_mode: beam
model_args:
  num_classes: 1296
  hidden_size: 1024
  c2d_type: slowfast101 #resnet18, mobilenet_v2, squeezenet1_1, shufflenet_v2_x1_0, efficientnet_b1, mnasnet1_0, regnet_y_800mf, vgg16_bn, vgg11_bn, regnet_x_800mf, regnet_x_400mf, densenet121, regnet_y_1_6gf
  conv_type: 2
  kernel_size: ['K5', "P2", 'K5', "P2"]
  use_bn: 1
  # SMKD
  share_classifier: 1
  weight_norm: True
  slowfast_config: SLOWFAST_64x2_R101_50_50.yaml

#model: models.build_function.build_tlp
#decode_mode: beam
#model_args:
#  num_classes: 1296
#  c2d_type: resnet18
#  kernel_size: ['K5', "P2", 'K5', "P2"]
#  stride: [ 4 , 0 ]
#  use_bn: 1

wandb:
  enable : true
  project : "openslr"
  entity : "3149409895-inner-mongolia-university-org"
