feeder: dataset.dataloader_video.VideoDataset
phase: train
dataset: phoenix2014
num_epoch: 80
work_dir: /share/huaiwen_group/guozihang/www2026_tlp_ph/
batch_size: 2

wandb:
  enable : true
  project : "openslr"
  entity : "gzhlaker"


random_seed: 0
test_batch_size: 2
num_worker: 8
device: 0,1,2
log_interval: 200
eval_interval: 1
save_interval: 5
loss_weights:
  ConvCTC: 1.0
  SeqCTC: 1.0
  Dist: 25.0
  Cu: 0.001
  Cp: 0.001

optimizer_args:
  optimizer: Adam
  base_lr: 0.0001
  step: [ 40, 60]
  learning_ratio: 1
  weight_decay: 0.0001
  start_epoch: 0
  nesterov: False

feeder_args:
  mode: 'train'
  datatype: 'memmap'
  num_gloss: -1
  drop_ratio: 1.0
  frame_interval: 1
  image_scale: 1.0

model: models.build_function.build_tlp
decode_mode: beam
model_args:
  spatio_module:
    [
      a:
        param1:
      b:
    ]
  num_classes: 1296
  c2d_type: resnet18
  kernel_size: ['K5', "P2", 'K5', "P2"]
  stride: [ 4 , 0 ]
  use_bn: 1
